### ISSUE TITLE
How to specify PVE Token ?

### ISSUE THREAD

**Issue by mickaelmonsieur** [juhnny5/pulumi-proxmox-cloud-init#1]
Hi,

I have created a PVE token : 

pveum user token add pulumi@pve pulumi -expire 0 -privsep 0 -comment "Pulumi token"

How to use ?

If i use : export PROXMOX_VE_PASSWORD="xxx-xxx-xxx"

I have this error: 

  proxmoxve:VM:VirtualMachine (vm1):
    error: 1 error occurred:
    	* error cloning VM: failed to authenticate HTTP POST request (path: nodes/virtdev/qemu/9000/clone) - Reason: failed to authenticate: failed to authenticate: received an HTTP 401 response - Reason: authentication failure

Thanks

**Comment by juhnny5** [comment]
Hi @mickaelmonsieur , 

I've just realized an error, you shouldn't specify the token but directly the password, I'll correct it so that I only specify the token.

In the meantime, the variable is aptly named:
```
export PROXMOX_VE_PASSWORD="my_password"
```

User password `pulumi@pve`.
